### ISSUE TITLE
ImportError: No module named fastimport.commands

### ISSUE THREAD

**Issue by ligi** [larsks/git-remote-ipfs#2]
I just tried to push for the first time and got this error:

```
git push ipfs fix_documentation 
Traceback (most recent call last):
  File "/usr/local/bin/git-remote-ipfs", line 9, in <module>
    load_entry_point('git-remote-ipfs==0.1', 'console_scripts', 'git-remote-ipfs')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/git_remote_ipfs/main.py", line 9, in <module>
  File "build/bdist.linux-x86_64/egg/git_remote_ipfs/remote.py", line 9, in <module>
ImportError: No module named fastimport.commands

```

**Comment by ssebbass** [comment]
Same issue here :(

**Comment by sneak** [comment]
I manually did a `pip install --user fastimport` and then it gives me:

```
01:57 $ git push ipfs master
Traceback (most recent call last):
  File "/Users/sneak/Library/Python/2.7/bin/git-remote-ipfs", line 9, in <module>
    load_entry_point('git-remote-ipfs==0.1', 'console_scripts', 'git-remote-ipfs')()
  File "/Users/sneak/Library/Python/2.7/lib/python/site-packages/git_remote_ipfs/main.py", line 52, in main
    helper.run()
  File "/Users/sneak/Library/Python/2.7/lib/python/site-packages/git_remote_ipfs/helper.py", line 49, in run
    handler(command, args)
  File "/Users/sneak/Library/Python/2.7/lib/python/site-packages/git_remote_ipfs/helper.py", line 74, in do_export
    importer.process(parser.iter_commands)
  File "/Users/sneak/Library/Python/2.7/lib/python/site-packages/fastimport/processor.py", line 75, in process
    self._process(command_iter)
  File "/Users/sneak/Library/Python/2.7/lib/python/site-packages/fastimport/processor.py", line 87, in _process
    handler(self, cmd)
  File "/Users/sneak/Library/Python/2.7/lib/python/site-packages/git_remote_ipfs/importer.py", line 22, in commit_handler
    self.repo.add_commit(cmd)
  File "/Users/sneak/Library/Python/2.7/lib/python/site-packages/git_remote_ipfs/remote.py", line 197, in add_commit
    self.resolve_marks(obj)
  File "/Users/sneak/Library/Python/2.7/lib/python/site-packages/git_remote_ipfs/remote.py", line 185, in resolve_marks
    fspec.dataref = self.marks.from_mark(fspec.dataref)
  File "/Users/sneak/Library/Python/2.7/lib/python/site-packages/git_remote_ipfs/marks.py", line 46, in from_mark
    return self.marks[mark]
KeyError: '2d521c390da1ccef423d6c4d2660b5866da31438'
fatal: Error while running fast-export
```
